In [2]:
import numpy as np

## One Dimension Array

In [6]:
a = np.array([1, 2, 3])
print(a)
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3


## Two Dimession Array

In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)
print(b[0][1])
print(b[0, 1])
print(b.ndim) #ndim adalah property untuk mengetahui dimensi dari array
print(b.size) #size adalah property untuk mengetahui jumlah elemen dari array
print(b.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
2
2
6
4


In [14]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.complex64)
print(b)
print(b.itemsize)


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
8


## Zeros, Ones, Arange and Linespace Function

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
a = np.arange(10, 30, 5) #arrange adalah fungsi untuk membuat array dengan range tertentu
print(a)

[10 15 20 25]


In [19]:
b = np.linspace(0, 2, 9) #linspace adalah fungsi untuk membuat array dengan range tertentu dengan jumlah elemen tertentu
print(b)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


## Reshape Fuction

In [22]:
a = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)
print(a)
print(a.shape)

b = a.reshape(4, 2)
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


## Ravel Function

In [24]:
a = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)
print(a)
print(a.shape)
a = a.ravel() #ravel adalah fungsi untuk membuat array 1 dimensi dari array 2 dimensi
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)


## Max, Min, Sum, Sqrt and Std Function

In [30]:
a = a.reshape(2, 4)
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.sum(axis=0)) #axis=0 adalah sum dari kolom
print(a.sum(axis=1)) #axis=1 adalah sum dari baris
print(np.sqrt(a)) #sqrt adalah fungsi untuk menghitung akar dari setiap elemen array
print(np.std(a)) #std adalah fungsi untuk menghitung standard deviasi dari setiap elemen array

[[1 2 3 4]
 [5 6 7 8]]
36
1
8
[ 6  8 10 12]
[10 26]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
2.29128784747792


## Operasi Arimetika 

In [31]:
a = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)
b = np.array(
    [
        [5, 6],
        [7, 8]
    ]
)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b)) #dot adalah fungsi untuk menghitung perkalian matrix
print(np.dot(a, b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
