In [2]:
"""
Slicing adalah sebuah teknik untuk mengambil sebagian data dari sebuah list, tuple, atau string.
Slicing pada list dan tuple mengembalikan sebuah list atau tuple baru.
Sedangkan slicing pada string mengembalikan sebuah string baru.
"""
import numpy as np

# Slicing

## One Dimension

In [3]:
# 1. Slicing List
# Slicing list dilakukan dengan menggunakan operator :
# [start:stop:step]
# start = index awal
# stop = index akhir (tidak inclusive)
# step = jarak antar index
# start, stop, dan step bersifat opsional
# jika tidak diberikan nilai, maka:
# start = 0
# stop = len(list)
# step = 1

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[0:4])  # [1 2 3 4]
print(arr[-2:4:-1])  # []
#penjelasan:
# -1 adalah index terakhir
# 4 adalah index ke 4

print(arr.shape)

[1 2 3 4]
[7 6]
(8,)


## Two Dimension

In [4]:
arr = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)
print(arr[0:2, 0:2])  # [[1 2] [5 6]]
#penjelasan:
# 0:2 -> mengambil baris 0 dan 1
# 0:2 -> mengambil kolom 0 dan 1

arr = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)
print(arr[0:2,3])
#penjelasan:
# 0:2 -> mengambil baris 0 dan 1
# 3 -> mengambil kolom 3


[[1 2]
 [5 6]]
[4 8]


## Three Dimension

In [5]:
arr = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9,10,11,12]
    ]
)
print(arr[0:2,0:2])
print()
for row in arr:
    print(row)
print()
for cell in arr.flat: #mengubah menjadi 1 dimensi
    print(cell)

[[1 2]
 [5 6]]

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

1
2
3
4
5
6
7
8
9
10
11
12


# Stacking

In [6]:
"""
Stacking adalah sebuah teknik untuk menggabungkan beberapa array menjadi satu array baru.
"""
# 2. Stacking Array
# Stacking array dilakukan dengan menggunakan function np.vstack() dan np.hstack()
# np.vstack() digunakan untuk stacking secara vertikal
# np.hstack() digunakan untuk stacking secara horizontal

a = np.arange(1, 11).reshape(2, 5)
b = np.arange(11, 21).reshape(2, 5)
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


## Using vstack

In [7]:
c = np.vstack((a, b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Using hstack

In [8]:
d = np.hstack((a, b))
print(d)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


# Splitting

In [9]:
"""
Splitting adalah sebuah teknik untuk memisahkan 
sebuah array menjadi beberapa array yang lebih kecil.
"""
# 3. Splitting Array
# Splitting array dilakukan dengan menggunakan function np.hsplit() dan np.vsplit()
# np.hsplit() digunakan untuk splitting secara horizontal
# np.vsplit() digunakan untuk splitting secara vertikal 

a = np.arange(1, 26).reshape(5, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## Using vsplit and hsplit

In [13]:
c,d,e,f,g = np.hsplit(a, 5) #membagi menjadi 5 bagian kolom
print(c)
print(d)
print(e)
print(f)
print(g)
c,d,e,f,g = np.vsplit(a, 5) #membagi menjadi 5 bagian baris
print(c)
print(d)
print(e)
print(f)


[[ 1]
 [ 6]
 [11]
 [16]
 [21]]
[[ 2]
 [ 7]
 [12]
 [17]
 [22]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]]
[[ 4]
 [ 9]
 [14]
 [19]
 [24]]
[[ 5]
 [10]
 [15]
 [20]
 [25]]
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[[11 12 13 14 15]]
[[16 17 18 19 20]]


# Indexing with bolean

In [14]:
a = np.arange(1, 26).reshape(5, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
b = a > 10

In [19]:
a[b]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [21]:
a[b] = 100
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]
