In [5]:
"""
Iterate atau perulangan adalah salah satu fitur yang sangat penting dalam pemrograman. 
Dengan iterasi, kita bisa melakukan sesuatu secara berulang-ulang.
Python menyediakan dua statement untuk melakukan iterasi, yaitu for dan while.

dalam numpy, kita bisa menggunakan iterasi dengan menggunakan fungsi nditer() yang disediakan oleh numpy.
"""
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Using Flatten

In [6]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for row in a:
    for cell in row:
        print(cell) 

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for cell in a.flatten(): #fungsi flatten() digunakan untuk mengubah array 2D menjadi 1D
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


## Using nditer

In [10]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
for cell in np.nditer(a, order='F'): #order='F' digunakan untuk mengiterasi array dalam bentuk kolom
    print(cell)

0
4
8
1
5
9
2
6
10
3
7
11


In [11]:
for cell in np.nditer(a, order='C'): #order='C' digunakan untuk mengiterasi array dalam bentuk baris
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
for cell in np.nditer(a, flags=['external_loop']): #flags=['external_loop'] digunakan untuk mengiterasi array dalam bentuk baris
    print(cell)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
b = np.arange(3, 15).reshape(3,4)
print(b)
print(a)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [16]:
for a,b in np.nditer([a,b]):
    print(a, b) #mengiterasi dua array sekaligus

0 3
2 4
4 5
6 6
8 7
10 8
12 9
14 10
16 11
18 12
20 13
22 14
